version: '3.8'
services:
  web:
      image: fast_api
      build: .
      ports:
        - '8000:8000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"